<a href="https://colab.research.google.com/github/Chandu965/my.1portfolio/blob/main/NumpyExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

R.chandu,
21BCE9655

Numpy Exercises


import numpy as np


In [1]:
import numpy as np
d=np.zeros(10)
d


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

create an array of 10 1's


In [2]:
d=np.ones(10)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

create an array of 10 fives

In [3]:
d=np.full(10,5.0)
d

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

create an array of the integers from 10 to 50

In [5]:
d=np.arange(10,51)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

create a 3*3 matrix values ranging from 0 to 8

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

create a 3*3 identity matrix

In [8]:
d=np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

use numpy to generate a random number between and 1

In [9]:
ran_num=np.random.rand()
ran_num

0.6094805237155254

In [10]:
a=np.random.randn(25)
a

array([ 1.55743812, -0.96255949,  0.15255463, -1.20904752,  1.94923523,
       -1.43951709, -2.19563449,  0.36913381, -0.88252061, -1.34445821,
        2.15700803, -0.7036283 ,  0.28685462, -0.10252841,  0.46289627,
        1.14872342, -0.21546169,  0.53491407, -0.79844481, -1.73680226,
        1.23601857,  0.66654803,  2.49264087, -0.72068751, -0.7293505 ])

crate the following matrix

In [11]:
d=np.arange(0.01,1.0,0.01)
d

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

create an array of 20 linearly spaced points between 0 and 1

In [12]:
la=np.linspace(0,1,20)
la

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

numpy indexing and selection

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
mat[3,4]

20

In [16]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [17]:
mat[4]

array([21, 22, 23, 24, 25])

In [18]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
mat.sum()

325

In [ ]:
mat.std()

In [20]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])